pipeline {
    agent any

    tools {
        jdk 'JDK17' // Reemplaza con tu versión de JDK configurada en Jenkins
        gradle 'GRADLE_HOME' // Reemplaza con tu configuración de Gradle en Jenkins
        dockerTool 'docker'
    }

    environment {
        DOCKER_IMAGE = 'juancorral/room-scout-backend'
        DOCKER_CREDENTIALS = 'dockerhub-credentials-id' // ID de credenciales de DockerHub
    }

    stages {
        stage('Clonar Repositorio') {
                    steps {
                        git branch: 'develop', url: 'https://github.com/arizaxel16/Room-Scout.git'
                    }
                }

        stage('Configurar Permisos') {
            steps {
                dir('backend/room-scout') {
                    sh 'chmod +x gradlew'
                }
            }
        }

        stage('Compilar y Construir') {
            steps {
                dir('backend/room-scout') {
                    sh './gradlew clean build --daemon'
                }
            }
        }
        stage('Run Tests with Coverage') {
            steps {
                dir('backend/room-scout') {
                    sh './gradlew test jacocoTestReport --daemon'  // Ejecuta los tests y genera el reporte de cobertura
                }
            }
        }

        stage('Análisis SonarQube') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    dir('backend/room-scout') {
                        sh './gradlew sonarqube'
                    }
                }
            }
        }

        stage('Esperar Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Construir Imagen Docker') {
            steps {
                script {
                    def image = docker.build("${DOCKER_IMAGE}:${env.BRANCH_NAME}-${env.BUILD_NUMBER}", "backend/room-scout/")

                    sh "docker images"
                }
            }
        }

        stage('Trivy Vulnerability Scan') {
            steps {
                script {
                    sh """
                    docker run --rm \
                      -v /var/run/docker.sock:/var/run/docker.sock \
                      -v $HOME/Library/Caches:/root/.cache/ \
                      aquasec/trivy image --severity HIGH,CRITICAL \
                      ${DOCKER_IMAGE}:${env.BRANCH_NAME}-${env.BUILD_NUMBER}
                    """
                }
            }
        }

        stage('Subir Imagen a DockerHub') {
            when {
                branch 'main'
                branch 'develop'
            }
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS}") {
                        def image = docker.image("${DOCKER_IMAGE}:${env.BRANCH_NAME}-${env.BUILD_NUMBER}")
                        image.push()
                    }
                }
            }
        }
    }

    post {
        always {
            junit 'backend/room-scout/build/test-results/test/*.xml'
            cleanWs()
        }
        failure {
            echo 'Build Failed'
        }
        success {
            echo 'Build Succeeded'
        }
    }
}