name: Docker Build and Push

on:
  push:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Login en DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/room-scout-frontend:latest ./frontend

      # 4. Escanear la imagen con Trivy
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/room-scout-frontend:latest
          format: table
          severity: HIGH,CRITICAL  # Cambia si quieres incluir más niveles de severidad
          exit-code: "1"  # Si encuentra vulnerabilidades críticas, fallará el job

      # 5. Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/room-scout-frontend:latest
